"""initial schema - 7 tables

Revision ID: 3e0b26118647
Revises: 
Create Date: 2026-04-21 03:28:10.431794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0b26118647'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battle_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('format_version', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('battlefield_config_id', sa.String(), nullable=False),
    sa.Column('player_deck_config_id', sa.String(), nullable=False),
    sa.Column('opponent_deck_config_id', sa.String(), nullable=False),
    sa.Column('rules_config_id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battlefield_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('format_version', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_instances',
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('definition_id', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('instance_id')
    )
    op.create_table('deck_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('format_version', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('general_definition_id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_card_instances',
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('definition_id', sa.String(), nullable=False),
    sa.Column('deployments_remaining', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('instance_id')
    )
    op.create_table('rules_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('format_version', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('troop_card_definitions',
    sa.Column('definition_id', sa.String(), nullable=False),
    sa.Column('card_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('faction', sa.String(), nullable=False),
    sa.Column('card_class', sa.String(), nullable=False),
    sa.Column('base_power', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('definition_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('troop_card_definitions')
    op.drop_table('rules_configs')
    op.drop_table('hero_card_instances')
    op.drop_table('deck_configs')
    op.drop_table('card_instances')
    op.drop_table('battlefield_configs')
    op.drop_table('battle_definitions')
    # ### end Alembic commands ###
