"""Player state repository port — append-only versioned persistence."""

from abc import ABC, abstractmethod

from ..entities.player_state import PlayerState


class PlayerStateRepository(ABC):
    """Append-only versioned persistence for player state.

    Play-time port — state is generated by players interacting with
    the game. Each save creates a new version snapshot.
    """

    @abstractmethod
    async def save(self, state: PlayerState) -> PlayerState:
        """Save a new version of the player state.

        The repository assigns the next version number and sets
        `timestamp` to the current UTC time automatically.
        The `version` field on the input state is ignored.
        The caller may set `change_note` to describe what caused
        this version (e.g., "Card troop-01 gained 50 XP").
        Returns the state with the assigned version and timestamp.
        """
        ...

    @abstractmethod
    async def load(
        self, player_id: str, version: int | None = None
    ) -> PlayerState | None:
        """Load a player's state.

        If version is None, returns the latest version.
        If version is specified, returns that exact snapshot.
        Returns None if the player or version does not exist.
        """
        ...

    @abstractmethod
    async def list_versions(self, player_id: str) -> list[int]:
        """List all available version numbers for a player, in ascending order."""
        ...
